#let title = "RS5 Topic Fair"
#let author = "Simon Holm"
#let date = "Feburary - 2026"

#import "@local/tempst:0.1.0": *

 #note(
   title: title,
   author: author,
   date: date
 )

= Reseach supervisors and thair projects
+ *Lena Frischlich*, Media Psychologist/ Digital Communication
  + Healthy food on youtube.
  + What kinds of (un)-healthy food can be found on danish food
+ *Curd Knüpfer*, Political Science/ Political Communication
  + Rise of alternative news ecosystems
  + Use AI tools to systematically analyze content
+ *Anne Clausen*, Computational Communication Science
  + Natural Language Processing project
  + What are the dominant themes in tweets about AI, and how have they evolved over time?
+ *Hannah Decker*, Media Psychology
  + AI being politicaly biased
  + Citizens using AI for political voting decisions
+ *Lynge Asbjørn Møller*, Journalism Studies
  + Autogenerated news
  + How does AI in news affect credibility?

= The process
The supervisor is the "product owner" who coordinates that you run in the same direction

We have tree types of sessions

- Planning meeting & task clarification (today: theory), 
- group session (“sprint” “execution”, independently in the group), 
- status report to supervisor (“review meeting”), 
- presentation in class (“pitch” and “reflection”) and 
- one week later: Submission of the assignment

== Grading
- Presentations (10%)
- Written submissions: (all together 40%)
  - Assignment 1: Focus on theoretical rigor (15%)
    - Additional input session on the 10th of March - including presentation training
  - Assignment 2: Focus on methodological rigor (10%)
  - Assignment 3: Implementation and discussion (15%)
- Overall: 50% of your grade come from this research project
- the other 50% come from the multiple-choice exam covering the lecture

